ROKT/rokt-ux-helper-android

demoapp/build.gradle.kts, roktux/build.gradle.kts
Use the correct Typesafe project access notation when adding the module dependencies
Refactor the module import paths.
Tested the builds locally
-   [x] I have performed a self-review of my own code.
-   [ ] I have made corresponding changes to the documentation.
-   [ ] I have added tests that prove my fix is effective or that my feature works.
-   [ ] New and existing unit tests pass locally with my changes.
-   [ ] I have verified that CI completes successfully.
-   [x] All insignificant commits have been squashed.
=> Refactor the module path using the project identifier

.buildkite/pipeline.yml, Dockerfile, README.md, roktux/build.gradle.kts
Currently `./gradlew test` fails due to dependencies being incorrect. This PR adjusts the dependencies and adds clarity to the README
Fixes N/A
- Readme
- Pipeline
- Dependencies
Ran `./gradlew test`, `./gradlew lint` and `./gradlew build` locally
-   [X] I have performed a self-review of my own code.
-   [X] I have made corresponding changes to the documentation.
-   [ ] I have added tests that prove my fix is effective or that my feature works.
-   [X] New and existing unit tests pass locally with my changes.
-   [x] I have verified that CI completes successfully.
-   [ ] All insignificant commits have been squashed.
=> NOJIRA - Adjust test dependencies

.github/pull_request_template.md
Removing unused checkboxes.
Fixes [(issue)]
PR template
N/A
N/A
=> NOJIRA - Remove unused checkboxes on PR template

gradle/libs.versions.toml
This PR is to release the library version `0.2.0` which includes the bug fixes and enhancements.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-427))]
=> NI-427 Release lib version 0.2.0

.github/dependabot.yml
Add minimum spec for dependabot
Fixes [(issue)]
- Add dependabot
N/A
N/A
=> NOJIRA - Create dependabot.yml

modelmapper/consumer-rules.pro
Keep the model classes for deserialization
Add proguard rule in the exported proguard config of the library.
Tested locally in an example app
=> NoJira - Fix proguard issue when minify is enabled

build-logic/convention/build.gradle.kts, build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt, build-logic/convention/src/main/kotlin/AndroidLibraryMavenCentralPublishPlugin.kt, build-logic/convention/src/main/kotlin/com/rokt/roktux/AndroidCompose.kt, build-logic/convention/src/main/kotlin/com/rokt/roktux/KotlinAndroid.kt, build-logic/convention/src/main/kotlin/com/rokt/roktux/MavenCentralPublish.kt, build-logic/convention/src/main/kotlin/com/rokt/roktux/ProjectExtensions.kt, build-logic/convention/src/main/kotlin/com/rokt/roktux/publish/RoktMavenPublishExtension.kt, build.gradle.kts, demoapp/build.gradle.kts, demoapp/lint-baseline.xml, gradle/libs.versions.toml, modelmapper/build.gradle.kts, modelmapper/lint-baseline.xml, networkhelper/build.gradle.kts, networkhelper/lint-baseline.xml, roktux/build.gradle.kts, roktux/lint-baseline.xml, roktux/src/test/java/com/rokt/roktux/component/ImageComponentTest.kt, testutils/build.gradle.kts
This PR is to move the publishing logic to the plugins inside build-logic.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-434))]
- Tested locally publishing to mavenLocal
=> NI-434 Centralise Gradle Plugins

build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt, build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt, build-logic/convention/src/main/kotlin/com/rokt/roktux/MavenCentralPublish.kt
This PR is to update the flavour settings so each module can customise its own flavour settings.
Fixes [(No_Jira)]
- Tested by releasing the library locally
=> [No-Jira] Retrieve flavour settings from gradle.properties

roktux/src/main/java/com/rokt/roktux/component/BasicTextComponent.kt, roktux/src/main/java/com/rokt/roktux/component/IconComponent.kt, roktux/src/main/java/com/rokt/roktux/component/ModifierFactory.kt, roktux/src/main/java/com/rokt/roktux/component/ProgressIndicatorComponent.kt, roktux/src/main/java/com/rokt/roktux/component/RichTextComponent.kt, roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutContract.kt, roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt
Sent diagnostics event when font failed to load
Fixes [LAYOUT-1947](https://rokt.atlassian.net/browse/LAYOUT-1947)
Catch the font failures and send diagnostics events
Tested locally
=> LAYOUT-1947 - Fix font diagnostics events

CHANGELOG.md
Update changelog and release version to 0.3.0
=> NoJira - Update version and CHANGELOG.md

.github/workflows/full-release.yml
Fixed variable name in release script
Fixes [(issue)]
- Actions
N/A
N/A
=> NOJIRA - Correct variable used in release script

RELEASING.md
Given the latest release and need for making many builds proposing we add support for snapshots so there's always a latest version to test against. Additionally to simplify our work in the future I've added a proposal for handling hotfixes
- Releasing documentation
N/A
N/A
=> NOJIRA - Proposal for new release process factoring in hotfixes and snapshots

.github/workflows/release-from-main.yml
This PR is to updated the `version-changed` condition in the workflow to use the `any_changed` output instead of the `only_changed` output.
Fixes [(No_Jira)]
=> Update version-changed condition in workflow

.github/workflows/pr-notification.yml
Add notifications to GChat when a pull request is opened
- Workflows
=> NOJIRA - Add pull request notifications

roktux/src/main/java/com/rokt/roktux/component/DataImageCarouselComponent.kt, roktux/src/test/assets/DataImageCarouselComponent/DataImageCarousel_Basic_Properties.json, roktux/src/test/assets/DataImageCarouselComponent/DataImageCarousel_Center_Bottom_Alignment.json, roktux/src/test/assets/DataImageCarouselComponent/DataImageCarousel_Center_Start_Alignment.json, roktux/src/test/assets/DataImageCarouselComponent/DataImageCarousel_Default_Alignment.json, roktux/src/test/assets/DataImageCarouselComponent/DataImageCarousel_Indicator_Center_Alignment.json, roktux/src/test/assets/DataImageCarouselComponent/DataImageCarousel_Indicator_End_Alignment.json, roktux/src/test/assets/DataImageCarouselComponent/DataImageCarousel_Indicator_Top_Alignment.json, roktux/src/test/assets/offer/Offer_with_image_carousel_key.json, roktux/src/test/java/com/rokt/roktux/component/DataImageCarouselComponentTest.kt
This PR is to integrate DataImageCarousel UI Component.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-577))]
- Unit tests have been added and tested in SDK too with mock Json.
=> NI-577 Implement Data Image Carousel

.github/actions/setup-java/action.yml, .github/workflows/draft-release-publish.yml, .github/workflows/pull-request.yml, .github/workflows/release-from-main.yml, .trunk/custom/validate-action-versions.py, .trunk/trunk.yaml
Pinning commits for actions to the commits from their latest tags. Also adding a custom trunk linter to enforce usage of commit pinning (excluding those from ROKT/rokt-workflows), as well as actionlint.
Fixes NOJIRA
- Bumped trunk and plugin versions
- Added custom linter to enforce commit pinning
- Fixed lint violations
Prior to pinning: https://github.com/ROKT/rokt-ux-helper-android/actions/runs/13914256598/job/38934303562
After pinning: https://github.com/ROKT/rokt-ux-helper-android/actions/runs/13914629991
Will create a ticket to move this to a centralised repo so that it is reusable by trunk in different projects
=> NOJIRA Update Actions

CHANGELOG.md, demoapp/src/main/java/com/rokt/demoapp/ui/screen/tutorials/TutorialNavGraph.kt, demoapp/src/main/java/com/rokt/demoapp/ui/screen/tutorials/TutorialState.kt, demoapp/src/main/java/com/rokt/demoapp/ui/screen/tutorials/nine/TutorialNineCompose.kt, demoapp/src/main/java/com/rokt/demoapp/ui/screen/tutorials/nine/TutorialNineViewModel.kt, demoapp/src/main/java/com/rokt/demoapp/ui/state/UiState.kt, modelmapper/src/main/java/com/rokt/modelmapper/mappers/ComplexModelMapper.kt, modelmapper/src/main/java/com/rokt/modelmapper/mappers/ContainerModelMapper.kt, modelmapper/src/main/java/com/rokt/modelmapper/mappers/ExperienceModelMapperImpl.kt, modelmapper/src/main/java/com/rokt/modelmapper/uimodel/LayoutSchemaUiModel.kt, roktux/src/main/java/com/rokt/roktux/component/CatalogStackedCollectionComponent.kt, roktux/src/main/java/com/rokt/roktux/component/LayoutUiModelFactory.kt, roktux/src/main/java/com/rokt/roktux/component/button/CatalogResponseComponent.kt, roktux/src/main/java/com/rokt/roktux/event/RoktEvent.kt, roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutContract.kt, roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt, settings.gradle.kts
Merging thank you page workstation to main.
Fixes [NI-741](https://rokt.atlassian.net/browse/NI-741)
Includes the following PR:
https://github.com/ROKT/rokt-ux-helper-android/pull/8
Databinding changes and tests were included in an already merged PR
=> NI-741 Merge Thank You Page Workstation

roktux/src/main/java/com/rokt/roktux/component/DataImageCarouselComponent.kt
- add an additional check for images corresponding to the color scheme of the app.
- only show indicator if image is available.
=> fix hide indicator if no images in dark mode

README.md
Adding small details on releasing and publishing locally.
Fixes [NI-770](https://rokt.atlassian.net/browse/NI-770)
- Added guide on local publishing
=> NI-770 Update README

.cortex/catalog/ux-helper-android.yaml, .github/CODEOWNERS
Update ownership and team of the repo
=> NoJira - Update ownership and team of the repo

.github/workflows/draft-release-publish.yml
* Use bump-semver plugin replacing custom script
* Generate a token and use it to create release PR
* Remove label in PR
* Use bump-semver plugin replacing custom script
* Generate a token and use it to create release PR
* Remove label in PR
=> NoJira - Refactor draft release workflow

.github/workflows/draft-release-publish.yml
Change the VERSION file and add it to the release draft PR
=> NoJira - Fix VERSION file update

settings.gradle.kts
For ease of development this PR adds Maven local to the list of resolvable repos
=> chore: Add Maven local to repos

CHANGELOG.md, roktux/src/main/java/com/rokt/roktux/component/CarouselDistributionComponent.kt
Provide a summary of why you are making this pull request and the issue it is fixing. Also include relevant motivation and context that a reviewer should know. List any dependencies that are required for this change.
Fixes SQDSDKS-7605
Padding on 
| Before        | After         |
|---------------|---------------|
|   <img width="380" src="https://github.com/user-attachments/assets/b2093594-b202-468e-a363-7204bcfed172" />  | <img width="380" src="https://github.com/user-attachments/assets/394407bb-d570-4d76-8810-2542b07f26d9" />  |
N/A
=> feat: CarouselDistribution - Only apply peekthrough padding horizontally

CHANGELOG.md, modelmapper/src/main/java/com/rokt/modelmapper/uimodel/LayoutSchemaUiModel.kt, roktux/src/main/java/com/rokt/roktux/component/CarouselDistributionComponent.kt, roktux/src/main/java/com/rokt/roktux/component/LayoutVariantMarketingComponent.kt, roktux/src/main/java/com/rokt/roktux/extensions/LayoutSchemaUiModelExtensions.kt, roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutUiState.kt, roktux/src/test/java/com/rokt/roktux/extensions/LayoutSchemaUiModelExtensionsTest.kt
Provide a summary of why you are making this pull request and the issue it is fixing. Also include relevant motivation and context that a reviewer should know. List any dependencies that are required for this change.
Fixes SDKE-40
- CarouselDistribution
https://github.com/user-attachments/assets/916b5885-f05e-4c54-8271-7a3066ef9f0e
https://github.com/user-attachments/assets/999aa969-1a5e-436e-b9f9-f8e5b9f7ec0c
N/A
=> feat: Allow for fit height carousel layouts

CHANGELOG.md
Correct changelog for CarouselDistribution fix
=> chore: Correct changelog for CarouselDistribution fix
