ROKT/rokt-ux-helper-android

.buildkite/pipeline.yml
.editorconfig
.trunk/.gitignore
.trunk/configs/.markdownlint.yaml
.trunk/configs/.shellcheckrc
.trunk/configs/.yamllint.yaml
.trunk/trunk.yaml

We want to add linting pre-commit/push and to the CI pipeline. This PR adds Trunk to the project as well as the trunk plugin to the Buildkite pipeline.
Fixes [NI-298](https://rokt.atlassian.net/browse/NI-298)
- Added trunk with cli version 1.22.8
Trunk step in the CI pipeline passes
There are some lint issues, will address them in a future PR.
~There is an issue with the current stable version of trunk, the beta version has been recommended as a fix~
Stable version has been released
-   [x] I have performed a self-review of my own code.
-   [ ] I have made corresponding changes to the documentation.
-   [ ] I have added tests that prove my fix is effective or that my feature works.
-   [x] New and existing unit tests pass locally with my changes.
-   [x] I have verified that CI completes …

NI-298 Add Trunk for Linting

---

roktux/src/main/java/com/rokt/roktux/component/button/CreativeResponseComponent.kt

Our automated tests require the resource id to be set on the creative response buttons in order for them to be recognised by the framework. This adds the required ids to the creative response button when the build config is Debug.
Fixes [NI-336](https://rokt.atlassian.net/browse/NI-336)
- Added test tags and represent them as resource ids for creative response button.
Verified via Appium:
-   [x] I have performed a self-review of my own code.
-   [ ] I have made corresponding changes to the documentation.
-   [ ] I have added tests that prove my fix is effective or that my feature works.
-   [x] New and existing unit tests pass locally with my changes.
-   [x] I have verified that CI completes successfully.
-   [x] All insignificant commits have been squashed.

NI-336 Add Test Tags for Automated Tests

---

roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt

Since the LayoutVM is bound to the lifecycle of the composable, it's possible that the composable exits the composition and the VM is cleared before the event queue is fully processed. This change uses the replay cache on the events queue and sends the events after the coroutine is cancelled. It is similar to the docs [here](https://kotlinlang.org/docs/cancellation-and-timeouts.html#run-non-cancellable-block)
This mostly affects embedded layouts as modal layouts typically have enough time for the events to be sent during the exit animation before the composable is removed.
Fixes [NI-356](https://rokt.atlassian.net/browse/NI-356)
- Cache the last 5 events in the events queue and send them if required when the vm is cleared and the coroutine to handle events is cancelled.
Verified via e2e …

NI-356 Send Final Events from Events Queue After Job is Cancelled

---

roktux/src/main/java/com/rokt/roktux/component/CarouselDistributionComponent.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt

When selecting the negative CTA then swiping back to the previous page, the negative button will no longer progress the carousel. This is because the target offer does not get updated correctly.
When tapping the negative CTA twice quickly, the scroll behaviour is stopped mid-animation and the carousel remains on the same page.
This PR aims to amend both of these issues.
Fixes [NI-375](https://rokt.atlassian.net/browse/NI-375)
- Update target offer when progressing via negative cta tap to keep it consistent
- Disable user scrolling while animating to the next offer to prevent the animation from being interrupted and the offer progression not being updated correctly.
Both behaviours:
https://github.com/user-attachments/assets/b579d0bb-a032-4d65-b687-5874cc2a7f1b
-   [x] I have performed a …

NI-375 Fix Negative Button and Scrolling Behaviour

---

modelmapper/src/main/java/com/rokt/modelmapper/model/NetworkLayoutVariant.kt
modelmapper/src/main/java/com/rokt/modelmapper/model/RootSchemaModelSerializer.kt

When serialising back, encode in the same format as it was received
Fixes [LAYOUT-1770](https://rokt.atlassian.net/browse/LAYOUT-1770)
Serialization of the DCUI JSON field
Tested locally

LAYOUT-1770 - Serialize DCUI JSON in the same string format

---

build.gradle.kts
gradle/libs.versions.toml
modelmapper/build.gradle.kts
roktux/build.gradle.kts

Currently the publishing logic is duplicated across the `modelmapper` and `roktux` modules.
Fixes N/A
Moved the logic to the root build.gradle.kts
Tested locally using `./gradlew check publishMavenPublicationToMavenLocal`
**modelmapper**
**roktux**
N/A

NOJIRA - Centralise logic for maven publish

---

roktux/src/main/java/com/rokt/roktux/event/RoktEvent.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt
roktux/src/test/java/com/rokt/roktux/viewmodel/RoktLayoutViewModelTest.kt

Trigger SignalLoadComplete when layout load is completed
Fixes [LAYOUT-1902](https://rokt.atlassian.net/browse/LAYOUT-1902)
* Fix the `parentGuid` of layout's `SignalInitialize` and set it correctly as plugin's instanceGuid
* Trigger SignalLoadComplete when layout load is completed

LAYOUT-1902 - Trigger SignalLoadComplete when layout load is completed

---

roktux/src/main/java/com/rokt/roktux/RoktLayout.kt
roktux/src/main/java/com/rokt/roktux/di/layout/LayoutComponent.kt
roktux/src/main/java/com/rokt/roktux/di/layout/LayoutModule.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/component/DIComponentViewModel.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt
roktux/src/test/java/com/rokt/roktux/testutil/DcuiComponentRule.kt
roktux/src/test/java/com/rokt/roktux/viewmodel/RoktLayoutViewModelTest.kt

`SignalImpression` signal for layout need to have the correct metadata.
Fixes [LAYOUT-1906](https://rokt.atlassian.net/browse/LAYOUT-1906)
* Receive the start timestamp from the user(or default it to current timestamp)
* Include the  `pageSignalLoadStart`, `pageSignalLoadComplete` and `pageRenderEngine` metadata in `SignalImpression` event
Tested locally

LAYOUT-1906 - Implement SignalImpression with correct metadata

---

roktux/src/main/java/com/rokt/roktux/event/RoktEvent.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt
roktux/src/test/java/com/rokt/roktux/viewmodel/RoktLayoutViewModelTest.kt

* SignalInitialize is sent when the SDK receives the data and before start rendering.
* Add default metadata in the events object
Fixes [LAYOUT-1929](https://rokt.atlassian.net/browse/LAYOUT-1929)
Fix the SignalInitialize sent from the SDK
Tested locally

LAYOUT-1929 - Fix SignalInitialize duplicate issue

---

roktux/src/main/java/com/rokt/roktux/component/CarouselDistributionComponent.kt

Call the `onEventSent` once per event
Fixes [LAYOUT-1929](https://rokt.atlassian.net/browse/LAYOUT-1929)
Fix the condition in Carousel component 
Tested locally 

LAYOUT-1929 - Fix duplicate SignalResponse events from CarouselDistributionComponent

---

modelmapper/src/main/java/com/rokt/modelmapper/mappers/DisplayModelMapper.kt

- This PR is to address the corner radius issue with Bottomsheet where only the top corner radius should be applied.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-484))]
- Tested with the Mock.

NI-484_Enable_top_corner_radius_bottomsheet

---

build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt
roktux/src/main/res/values/rokt_attrs.xml

This PR is to force a prefix `rokt` for all resources in the Android library.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-485))]

update the resources to use Rokt Prefix

---

roktux/src/main/java/com/rokt/roktux/RoktLayout.kt

When the layout is loaded from cache and the state is dismissed, trigger `LayoutCompleted` uxEvent to let the consumer know.
Fixes [LAYOUT-1970](https://rokt.atlassian.net/browse/LAYOUT-1970)
Trigger UxEvent when the layout cannot be loaded because the saved state is dismissed
Tested with stage environment

LAYOUT-1970 - Fix the empty overlay issue

---

roktux/src/main/java/com/rokt/roktux/component/ModifierFactory.kt

When the requested fontFamily is not available, send the diagnostic error
Fixes LAYOUT-1967
Fix sending null as failed fontFamily in diagnostics
Tested with demo layouts

LAYOUT-1967 - Send font diagnostics errors when requested value is not null

---

roktux/src/main/java/com/rokt/roktux/di/core/Component.kt
roktux/src/main/java/com/rokt/roktux/di/core/Factory.kt
roktux/src/main/java/com/rokt/roktux/di/core/Module.kt
roktux/src/main/java/com/rokt/roktux/di/layout/LayoutModule.kt
roktux/src/main/java/com/rokt/roktux/di/variants/marketing/MarketingModule.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/composablescoped/ComposableScopedViewModel.kt

This PR is to add lazy initialization to the core DI classes in the `roktux` project.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-403))]

Ni 403 expose core di classes

---

CHANGELOG.md
roktux/src/main/java/com/rokt/roktux/component/BottomSheetComponent.kt
roktux/src/main/java/com/rokt/roktux/component/ModifierFactory.kt
roktux/src/test/assets/BottomSheetComponent/BottomSheet_with_height.json
roktux/src/test/java/com/rokt/roktux/component/BottomSheetComponentTest.kt

The new material bottomsheet component is using the shape parameter to draw the container. The default shape is with a rounded corner one.
Create the shape and apply it when composing the `ModalBottomSheet` component.
Fixes [LAYOUT-2037](https://rokt.atlassian.net/browse/LAYOUT-2037)
Fix the bottomsheet border radius issue by applying the correct shape background
Tested locally with mock responses

LAYOUT-2037 - Fix bottomsheet border radius issue

---

CHANGELOG.md
modelmapper/src/main/java/com/rokt/modelmapper/uimodel/LayoutSchemaUiModel.kt
roktux/src/main/java/com/rokt/roktux/RoktLayout.kt
roktux/src/main/java/com/rokt/roktux/RoktLayoutView.kt
roktux/src/main/java/com/rokt/roktux/RoktUxConfig.kt
roktux/src/main/java/com/rokt/roktux/component/BottomSheetComponent.kt
roktux/src/main/java/com/rokt/roktux/component/OverlayComponent.kt
roktux/src/main/java/com/rokt/roktux/di/layout/LayoutComponent.kt
roktux/src/main/java/com/rokt/roktux/di/layout/LayoutModule.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/component/DIComponentViewModel.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt
roktux/src/test/java/com/rokt/roktux/testutil/DcuiComponentRule.kt
roktux/src/test/java/com/rokt/roktux/viewmodel/RoktLayoutViewModelTest.kt

This PR fixes the `edgeToEdgeDisplay` support in the `LayoutSchemaUiModel` and `RoktUxConfig` classes.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-562))]

NI-562 Edge to Edge display support

---

CHANGELOG.md
modelmapper/src/main/java/com/rokt/modelmapper/mappers/DisplayModelMapper.kt
modelmapper/src/main/java/com/rokt/modelmapper/mappers/ModifierMapper.kt
modelmapper/src/main/java/com/rokt/modelmapper/uimodel/LayoutSchemaUiModel.kt
roktux/src/main/java/com/rokt/roktux/component/ModifierFactory.kt
roktux/src/test/assets/RowComponent/Row_with_PressedStateBorder.json
roktux/src/test/java/com/rokt/roktux/component/RowComponentTest.kt
testutils/src/main/java/com/rokt/core/testutils/assertion/BorderAssertions.kt

Fix the issue with pressed state styles not being applied.
Fixes [LAYOUT-2076](https://rokt.atlassian.net/browse/LAYOUT-2076)
Apply the pressed style and default style of the current breakpoint if required.
Tested with mock json

LAYOUT-2076 - Fix the pressed state style issue - breakdown complex object

---

CHANGELOG.md
roktux/src/main/java/com/rokt/roktux/component/BasicTextComponent.kt
roktux/src/main/java/com/rokt/roktux/component/IconComponent.kt
roktux/src/main/java/com/rokt/roktux/component/ProgressIndicatorComponent.kt
roktux/src/test/assets/IconComponent/StaticIcon_with_TextColor.json
roktux/src/test/assets/ProgressIndicatorComponent/ProgressIndicator.json
roktux/src/test/assets/TextComponent/BasicText_with_TextColor.json
roktux/src/test/java/com/rokt/roktux/component/IconComponentTest.kt
roktux/src/test/java/com/rokt/roktux/component/ProgressIndicatorComponentTest.kt
roktux/src/test/java/com/rokt/roktux/component/TextComponentTest.kt

The DarkMode state was not used for constructing the styles of `BasicTextComponent`, `IconComponent` and `ProgressIndicatorComponent`.
Fixes [LAYOUT-2088](https://rokt.atlassian.net/browse/LAYOUT-2088)
Use the correct parameter to construct the styles so that the dark mode color is used.
Added tests to validate that the correct color is applied in light and dark modes.
Added unit tests and mock json.
Tested using mock json

LAYOUT-2088 - Fix text color in dark mode

---

roktux/src/main/java/com/rokt/roktux/component/OverlayComponent.kt

This PR is to fix the `allowBackdropToClose` for OverlayComponent which was triggered when we enable `edgeToedge` display.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-641))]

NI-641 Fix Overlay BackDrop Close

---

build-logic/convention/build.gradle.kts
gradle.properties
gradle/libs.versions.toml

Maven plugin has been updated with the RC that supports snapshots. This PR updates the version for testing pending full release.
[Ref](https://github.com/vanniktech/gradle-maven-publish-plugin/pull/894#issuecomment-2695419022)
- toml versions
N/A
N/A

NOJIRA - Update Maven plugin to RC that supports snapshots

---

gradle/libs.versions.toml

Maven plugin has been updated with the RC that supports snapshots. This PR updates to RC2 which fixes the 401 issue for testing pending full release.
[Ref](https://github.com/vanniktech/gradle-maven-publish-plugin/pull/910)
- Maven publish version
N/A
N/A

NOJIRA - Update maven publish to RC2

---

roktux/src/main/java/com/rokt/roktux/component/GroupedDistributionComponent.kt
roktux/src/main/java/com/rokt/roktux/component/ModifierFactory.kt
roktux/src/main/java/com/rokt/roktux/component/OneByOneDistributionComponent.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutContract.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt
roktux/src/test/java/com/rokt/roktux/viewmodel/RoktLayoutViewModelTest.kt

This PR is to address the issue where the `viewModelStore` is not set before the `NavHost` composable is used. NavHost composable sets the viewModelStore, so we do a pre-checking here.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-678))]
- Unit test has been added

NI-678 Try Setting viewModelStore before NavHost composable

---

roktux/src/main/java/com/rokt/roktux/event/RoktEvent.kt
roktux/src/main/java/com/rokt/roktux/viewmodel/layout/LayoutViewModel.kt
roktux/src/test/java/com/rokt/roktux/viewmodel/RoktLayoutViewModelTest.kt

Add `layoutId` to the `OpenUrl` event
Fixes [LAYOUT-2194](https://rokt.atlassian.net/browse/LAYOUT-2194)
*   Add layoutId to OpenUrl event to identify the layout that triggers the event.
*   Update unit tests
Unit tested

LAYOUT-2194 - Add layoutId to OpenUrl event

---

roktux/src/main/java/com/rokt/roktux/component/button/CreativeResponseComponent.kt

UI automation was using `testTagsAsResourceId` in order to lookup the button UI elements. 
Remove the test code as it is no longer used in UI automation
E2E automation tests

NoJira - Remove the test modifier from response component

---

CHANGELOG.md
roktux/src/main/java/com/rokt/roktux/component/ModifierFactory.kt

When children are drawn on top of rounded corner area it was drawing outside the background shape.
Fixes [LAYOUT-2268](https://rokt.atlassian.net/browse/LAYOUT-2268)
Clip to the shape so that the rounded corner shape is applied properly.
Tested with mock JSON
```json
"border": {
"borderColor": null,
"borderStyle": null,
"borderWidth": null,
"borderRadius": 40
}
```
| Before | After |
|--------|-------|
| <img src="https://github.com/user-attachments/assets/34c151e6-50e6-4d85-9bc6-062a6ea36417" width="200" /> | <img src="https://github.com/user-attachments/assets/29bcfc67-b2aa-481f-8e44-857a7671882e" width="200" /> |

LAYOUT-2268 - Fix the border radius issue

---

CHANGELOG.md
roktux/src/main/java/com/rokt/roktux/component/ImageComponent.kt
roktux/src/test/assets/ImageComponent/Image_with_AltText_empty.json
roktux/src/test/java/com/rokt/roktux/component/ImageComponentTest.kt

When the alt value is empty or null, remove the accessibility focus from the image component
Fixes [LAYOUT-2305](https://rokt.atlassian.net/browse/LAYOUT-2305)
Remove the accessibility content description and clear the semantics if the alt value is empty or null
Added unit tests
Tested locally
```
{
"light": "https://***r/Pica_pica_01.jpg",
"dark": "",
"alt": "This is a bird",
"title": ""
}
```
[Screen_recording_20250331_141954.webm](https://github.com/user-attachments/assets/d227c20d-8b9c-4dcb-86d6-5a01655017ee)
```
{
"light": "https://www.egretta.org/gallery/birds/Cyanistes_caeruleus_04.jpg",
"dark": "",
"alt": "",
"title": ""
}
```
[Screen_recording_20250331_142030.webm](https://github.com/user-attachments/assets/a6dd7ad7-f184-45f5-94b9-906617b62f56)

LAYOUT-2305 - Fix the accessibility readout in creative image component when alt text is empty

---

CHANGELOG.md
roktux/src/main/java/com/rokt/roktux/component/ImageComponent.kt

If the device is in light mode the image shows. If the device changes to dark mode the image is hidden. If the device goes back to light mode to image does not come back. This is because the error state is not being reset when dark mode status changes. 
Fixes NOJIRA
- Remember the error state using isDarkModeEnabled as the key
Tested locally where
Light mode (image shows) -> dark mode (image hidden) -> light mode (image returned)

NOJIRA Image Dark Mode Alternating Fix

---

CHANGELOG.md
roktux/src/main/java/com/rokt/roktux/component/ModifierFactory.kt
roktux/src/main/java/com/rokt/roktux/component/RichTextComponent.kt
roktux/src/test/assets/TextComponent/RichText_with_text_transformation.json
roktux/src/test/java/com/rokt/roktux/component/TextComponentTest.kt

The ModifierFactory was performing the transformation on the whole text including the html text. When the href url is transformed to caps, it fails to open in the browser.
Fixes [LAYOUT-2319](https://rokt.atlassian.net/browse/LAYOUT-2319)
-   Updated `applyTextProperties` to apply text transformation only when it is not `RichTextComponent`
-   Modified `RichTextComponent` to handle text transformations for html texts including link spans.
-   Added a test case to verify the text transformation functionality.
-   Added test cases to verify link click events.
-   Updated CHANGELOG with fix details.
Added unit tests. Tested locally

LAYOUT-2319 - Fix text transformation and html link behaviour in RichTextComponent

---

gradle/libs.versions.toml
modelmapper/build.gradle.kts
modelmapper/src/main/java/com/rokt/modelmapper/hmap/TypedKey.kt
modelmapper/src/test/java/com/rokt/modelmapper/hmap/TypedKeyTest.kt

The usage of reflection here was to ensure that fast-fail if someone were to inadvertently use a parameterised valued type as a value in `TypedKey`. Unfortunately the `typeParameters` method is not working when running via .NET MAUI and no attempts at adding proguard rules fixed it.
Since this check is more of a nice to have (since either way it will eventually throw an exception if used), this PR just removes it. The javadoc still mentions its an unsupported use-case.
Fixes NO-JIRA
- Removed the parameterised type check
- Removed the reflection library as this was the only usage
- After removing it and publishing locally MAUI was able to work

NOJIRA Remove Reflection Usage from TypedKey

---

.github/workflows/release-from-main.yml

Update the release workflow to always make snapshots for the next available version and update the Android SDK when a UX Helper release is made
- Release workflow
N/A

NOJIRA - Always generate snapshot, update Android SDK on release

---

CHANGELOG.md
roktux/src/main/java/com/rokt/roktux/component/ColumnComponent.kt
roktux/src/main/java/com/rokt/roktux/component/RowComponent.kt
roktux/src/test/assets/ColumnComponent/Column_with_StretchAlignment.json
roktux/src/test/assets/ColumnComponent/Column_with_StretchAlignment_child.json
roktux/src/test/assets/RowComponent/Row_with_StretchAlignment.json
roktux/src/test/assets/RowComponent/Row_with_StretchAlignment_child.json
roktux/src/test/java/com/rokt/roktux/component/ColumnComponentTest.kt
roktux/src/test/java/com/rokt/roktux/component/RowComponentTest.kt

Fix the stretch behaviour when the components are arranged in a Row/Column and the container stretch or alignSelf stretch properties are set
Fixes [LAYOUT-2339](https://rokt.atlassian.net/browse/LAYOUT-2339)
* When the container stretch is set, apply the intrinsic size and use the max height/width available.
* Use `fillMaxWidth` for column and `fillMaxHeight` for row when stretch is set.
* Added unit tests
Added unit tests to verify the changes
Used mock json to test the behaviour.
| Before                                                                                                                                                                                                                                     | After …

LAYOUT-2339 - Fix the component stretch behaviour

---

roktux/src/main/java/com/rokt/roktux/component/LayoutVariantMarketingComponent.kt
roktux/src/main/java/com/rokt/roktux/utils/Extensions.kt

Add obstruction and mis-size conditions for sending signalviewed signal
Fixes [LAYOUT-2302](https://rokt.atlassian.net/browse/LAYOUT-2302)
Add obstruction and mis-size conditions for sending signalviewed signal
Tested locally.

LAYOUT-2302 - Add criteria for signal viewed

---

CHANGELOG.md
modelmapper/src/main/java/com/rokt/modelmapper/mappers/ExperienceModelMapperImpl.kt
modelmapper/src/main/java/com/rokt/modelmapper/model/NetworkAction.kt
modelmapper/src/main/java/com/rokt/modelmapper/uimodel/ExperienceModel.kt

Add support for new Action type in Creative response object.
Fixes [SQDSDKS-7308](https://mparticle-eng.atlassian.net/browse/SQDSDKS-7308)
* Add new enum item for `NetworkAction`. Added `ExternalPaymentTrigger`
* Updated mappers
Tested locally with mock json

SQDSDKS-7308 - Add support for `ExternalPaymentTrigger` in Response Action

---

build-logic/convention/src/main/kotlin/com/rokt/roktux/MavenCentralPublish.kt

Replicates the functionality of the core Rokt SDK and allows for signing to be skipped when publishing to Maven to aid in local development
- Maven publish
- Ran `./gradlew publishMavenPublicationToMavenLocal -PVERSION=4.1337.0-SNAPSHOT -PSKIP_SIGN=true`
N/A

chore: Allow for skip sign when publishing
